### ISSUE TITLE
Find duplicates finds non-duplicates

### ISSUE THREAD

**Issue by colemar** [Isayso/PlaylistEditorTV#74]
PlaylistEditorTV v1.7.4

Hello, I loaded a playlist file that I have manually maintained before.
The structure of the file is like the following sample:
```
#EXTM3U

# Italia ------------------------------------------------------------------------------------------------------------
#EXTINF:0 tvg-logo="https://static.wikia.nocookie.net/logopedia/images/f/f7/Rai_1_2016.svg/revision/latest/scale-to-width-down/400" group-title="Italia",Rai 1
https://mediapolis.rai.it/relinker/relinkerServlet.htm?cont=2606803&output=16
#EXTINF:0 tvg-logo="https://static.wikia.nocookie.net/logopedia/images/8/89/Rai_2_2016.svg/revision/latest/scale-to-width-down/400" group-title="Italia",Rai 2
https://mediapolis.rai.it/relinker/relinkerServlet.htm?cont=308718&output=16


# Sport -------------------------------------------------------------------------------------------------------------
#EXTINF:0 tvg-logo="https://upload.wikimedia.org/wikipedia/commons/thumb/a/af/Sky_Sport_Uno_-_Logo_2020.svg/400px-Sky_Sport_Uno_-_Logo_2020.svg.png" group-title="Sport",Sky Sport UNO Italy
#EXTVLCOPT:http-referrer=https://weblivehdplay.ru/
https://ddy5.hlsjs.ru/ddy5/premium461/playlist.m3u8|referrer=https://weblivehdplay.ru/
#EXTINF:0 tvg-logo="https://upload.wikimedia.org/wikipedia/commons/thumb/a/af/Sky_Sport_Uno_-_Logo_2020.svg/400px-Sky_Sport_Uno_-_Logo_2020.svg.png" group-title="Sport",Sky Sport UNO diretto
#EXTVLCOPT:http-referrer=https://weblivehdplay.ru/
https://ddy5.hlsjs.ru/ddy5/premium461/tracks-v1a1/mono.m3u8|referrer=https://weblivehdplay.ru/

```

I believe there are no duplicates.
When I click "find duplicates" button, the application highlights some random lines. I do not understand why.

Attached iptv.m3u
[iptv.zip](https://github.com/Isayso/PlaylistEditorTV/files/13512257/iptv.zip)

**Comment by Isayso** [comment]
Because I cannot reply on github anymore (no two factor log in) please see my answer here

https://codeberg.org/Isayso/PlaylistEditorTV/issues/1#issuecomment-1366306
     On Thursday, November 30, 2023 at 12:41:59 PM GMT+1, colemar ***@***.***> wrote:  
 
 


PlaylistEditorTV v1.7.4

Hello, I loaded a playlist file that I have manually maintained before.
The structure of the file is like the following sample:
#EXTM3U# Italia ------------------------------------------------------------------------------------------------------------#EXTINF:0 tvg-logo="https://static.wikia.nocookie.net/logopedia/images/f/f7/Rai_1_2016.svg/revision/latest/scale-to-width-down/400" group-title="Italia",Rai 1https://mediapolis.rai.it/relinker/relinkerServlet.htm?cont=2606803&output=16#EXTINF:0 tvg-logo="https://static.wikia.nocookie.net/logopedia/images/8/89/Rai_2_2016.svg/revision/latest/scale-to-width-down/400" group-title="Italia",Rai 2https://mediapolis.rai.it/relinker/relinkerServlet.htm?cont=308718&output=16# Sport -------------------------------------------------------------------------------------------------------------#EXTINF:0 tvg-logo="https://upload.wikimedia.org/wikipedia/commons/thumb/a/af/Sky_Sport_Uno_-_Logo_2020.svg/400px-Sky_Sport_Uno_-_Logo_2020.svg.png" group-title="Sport",Sky Sport UNO Italy#EXTVLCOPT:http-referrer=https://weblivehdplay.ru/https://ddy5.hlsjs.ru/ddy5/premium461/playlist.m3u8|referrer=https://weblivehdplay.ru/#EXTINF:0 tvg-logo="https://upload.wikimedia.org/wikipedia/commons/thumb/a/af/Sky_Sport_Uno_-_Logo_2020.svg/400px-Sky_Sport_Uno_-_Logo_2020.svg.png" group-title="Sport",Sky Sport UNO diretto#EXTVLCOPT:http-referrer=https://weblivehdplay.ru/https://ddy5.hlsjs.ru/ddy5/premium461/tracks-v1a1/mono.m3u8|referrer=https://weblivehdplay.ru/
I believe there are no duplicates.
When I click "find duplicates" button, the application highlights some random lines. I do not understand why.

Attached iptv.m3u
iptv.zip
